version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: integrationhub-postgres
    restart: always
    environment:
      POSTGRES_USER: hub
      POSTGRES_PASSWORD: hubpass
      POSTGRES_DB: hubdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: